FROM python:3.9
ENV PYTHONBUFFERED 1
WORKDIR /app
COPY backend/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY backend /app/backend

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "backend:app"]
